<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.3.2.min.js'); ?>
<div class="col-main grid-full in-col1">
    <div class="account-login clearer">
        <div class="page-title">
            <h1>Нэвтрэх болон шинээр бүртгүүлэх</h1>
        </div>

    <div class="new-users grid12-6">
        <div class="content">
            <h2>Бүртгэлгүй хэрэглэгчид</h2>
            <p>Худалдааны нэгдсэнд системд нэгдсэнээр танд цаг хугацаа орон зайнаас хамааралгүй хүссэн бүтээгдхүүнээ авах боломж нээгдэх тул та бүртгүүлнэ үү.</p>
        </div>
        <div class="buttons-set">
            <button type="button" title="Шинээр бүртгүүлэх" class="button" onclick="window.location='<?php echo $this->url(array('module'=>'default',
        											'controller'=>'autentication',
        											'action'=>'signup')); ?>'"><span><span>Шинээр бүртгүүлэх</span></span></button>
        </div>
    </div>
    <div class="registered-users grid12-6">
        <div class="content">
            <h2>Бүртгэлтэй хэрэглэгчид</h2>
            <p>Та бүртгэлтэй бол энд нэвтэрч орно уу.</p>
            <?php 
                echo $this->form;
                echo $this->errorMessage;
            ?>
                <a href="http://ultimo.infortis-themes.com/demo/default/customer/account/forgotpassword/" class="f-left">Forgot Your Password?</a>

<script type="text/javascript">
//<![CDATA[
    function toggleRememberMepopup(event){
        if($('remember-me-popup')){
            var viewportHeight = document.viewport.getHeight(),
                docHeight      = $$('body')[0].getHeight(),
                height         = docHeight > viewportHeight ? docHeight : viewportHeight;
            $('remember-me-popup').toggle();
            $('window-overlay').setStyle({ height: height + 'px' }).toggle();
        }
        Event.stop(event);
    }

    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('window-overlay'));
        new Insertion.Bottom($$('body')[0], $('remember-me-popup'));

        $$('.remember-me-popup-close').each(function(element){
            Event.observe(element, 'click', toggleRememberMepopup);
        })
        $$('#remember-me-box a').each(function(element) {
            Event.observe(element, 'click', toggleRememberMepopup);
        });
    });
    //]]>
    </script>
                <p class="required">* Required Fields</p>
            </div>
        </div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
    </div>
</div>