<?php //$this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.3.2.min.js'); ?>
<?php

if(isset($this->errorMessage)){
            echo '<div class="alert alert-error">'.$this->errorMessage.'</div>';

}?>
<?php
if(isset($this->success)){
          echo '<div class="alert alert-success">Succesfully sign up. <a href="'.$this->url(array('module'=>'default',
											'controller'=>'autentication',
											'action'=>'login')).'">Login</a></div>';
}?>
                                <div class="preface grid-full in-col1"></div>
                <div class="col-main grid-full in-col1">
                                        <div class="account-create">
    <div class="page-title">
        <h1>Бүртгүүлэх</h1>
    </div>
        <div class="fieldset">
        <?php echo $this->form->renderForm(false) ?>
            <input type="hidden" name="success_url" value="">
            <input type="hidden" name="error_url" value="">
            <h2 class="legend">Хувийн мэдээлэл</h2>
            <ul class="form-list"> 
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <?php echo $this->form->firstname->renderLabel(); ?>
                            <div class="input-box">
                                <?php echo $this->form->firstname->renderViewHelper();?>
                            </div>
                        </div>
                        <div class="field name-lastname">
                            <?php echo $this->form->lastname->renderLabel(); ?>
                            <div class="input-box">
                                <?php echo $this->form->lastname->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <?php echo $this->form->email->renderLabel(); ?>
                    <div class="input-box">
                        <?php echo $this->form->email->renderViewHelper();?>
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend">Нэвтрэх мэдээлэл</h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <?php echo $this->form->password->renderLabel(); ?>
                        <div class="input-box">
                            <?php echo $this->form->password->renderViewHelper();?>
                        </div>
                    </div>
                    <div class="field">
                        <?php echo $this->form->confirmPassword->renderLabel(); ?>
                        <div class="input-box">
                            <?php echo $this->form->confirmPassword->renderViewHelper();?>
                        </div>
                    </div>
                </li> 
                <li id="captcha-input-box-user_create">
                    <?php echo $this->form->captcha->render();?>
                    <script type="text/javascript">//<![CDATA[
                   function refreshcapthca() { 
                            $.ajax({ 
                                url: '/book/public/autentication/refresh', 
                                dataType:'json', 
                                success: function(data) { 
                                    $('#captcha-input-box-user_create img').attr('src', data.src); 
                                    $('#captcha-id').attr('value', data.id); 
                                }
                            }); 
                        }
                    //]]></script>
                    <img id="refreshcaptcha" class="captcha-reload" src="<?php echo $this->baseUrl(); ?>/img/reload.png" alt="Reload captcha" onclick="refreshcapthca()">
                </li>          
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required">* Required Fields</p>
            <p class="back-link"><a href="<?php echo $this->url(array('module'=>'default',
        											'controller'=>'autentication',
        											'action'=>'login'))?>" class="back-link"><small>« </small>Буцах</a></p>
            <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>     
            

<script type="text/javascript">
//<![CDATA[
    function toggleRememberMepopup(event){
        if($('remember-me-popup')){
            var viewportHeight = document.viewport.getHeight(),
                docHeight      = $$('body')[0].getHeight(),
                height         = docHeight > viewportHeight ? docHeight : viewportHeight;
            $('remember-me-popup').toggle();
            $('window-overlay').setStyle({ height: height + 'px' }).toggle();
        }
        Event.stop(event);
    }

    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('window-overlay'));
        new Insertion.Bottom($$('body')[0], $('remember-me-popup'));

        $$('.remember-me-popup-close').each(function(element){
            Event.observe(element, 'click', toggleRememberMepopup);
        })
        $$('#remember-me-box a').each(function(element) {
            Event.observe(element, 'click', toggleRememberMepopup);
        });
    });
//]]>
</script>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
            //]]>
    </script>
</div>
                </div>
                <div class="postscript grid-full in-col1"></div>